# docker-compose -p bus_park_services_package --env-file settings.env up

services:
  redis:
    image: redis:latest
    container_name: redis_container
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    ports:
      - "${REDIS_PORT}:6379"

  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper_container
    ports:
      - "22181:2181"

  kafka:
    image: wurstmeister/kafka
    container_name: kafka_container
    depends_on:
      - zookeeper
    ports:
      - "${KAFKA_PORT}:${KAFKA_PORT}"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'false'
      KAFKA_CREATE_TOPICS: "${KAFKA_PATHS_BUSES_TOPIC}:3:1, ${KAFKA_BUSES_PATHS_TOPIC}:3:1, ${KAFKA_SCHEDULE_FROM_LOG_TOPIC}:3:1, ${KAFKA_SCHEDULE_FROM_DRIVERS_TOPIC}:3:1"